name       : tracker-miners
version    : 2.0.2
release    : 4
source     :
    - https://download.gnome.org/sources/tracker-miners/2.0/tracker-miners-2.0.2.tar.xz : cf417ece944c997f630dda41a7f5c449d609fa53dbb34fae7caa4c7af1e0e8ef
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.1
component  : desktop.gnome.core
summary    : Collection of data extractors for Tracker
description: |
    Collection of data extractors for Tracker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(exempi-2.0)
    - pkgconfig(flac)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gupnp-dlna-gst-2.0)
    - pkgconfig(icu-io)
    - pkgconfig(libavcodec)
    - pkgconfig(libcue)
    - pkgconfig(libexif)
    - pkgconfig(libgrss)
    - pkgconfig(libgsf-1)
    - pkgconfig(libgxps)
    - pkgconfig(libiptcdata)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libseccomp)
    - pkgconfig(poppler)
    - pkgconfig(libtiff-4)
    - pkgconfig(taglib)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-sparql-2.0)
    - pkgconfig(upower-glib)
    - pkgconfig(vorbisfile)
    - giflib-devel
    - libjpeg-turbo-devel
    - vala
setup      : |
    %configure --disable-static \
               --enable-libflac \
               --enable-libvorbis
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
