name       : tracker-miners
version    : 2.0.5
release    : 16
source     :
    - https://download.gnome.org/sources/tracker-miners/2.0/tracker-miners-2.0.5.tar.xz : 6499c083761631b14ad58d463c4af1d69bca842d9a3d11a6c456ced5d0b26802
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.gnome.core
summary    : Collection of data extractors for Tracker
description: |
    Collection of data extractors for Tracker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(exempi-2.0)
    - pkgconfig(flac)
    - pkgconfig(gexiv2)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gupnp-dlna-gst-2.0)
    - pkgconfig(icu-io)
    - pkgconfig(libavcodec)
    - pkgconfig(libcue)
    - pkgconfig(libexif)
    - pkgconfig(libgrss)
    - pkgconfig(libgsf-1)
    - pkgconfig(libgxps)
    - pkgconfig(libiptcdata)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libseccomp)
    - pkgconfig(libturbojpeg)
    - pkgconfig(poppler)
    - pkgconfig(libtiff-4)
    - pkgconfig(taglib)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-sparql-2.0)
    - pkgconfig(upower-glib)
    - pkgconfig(vorbisfile)
    - giflib-devel
    - vala
setup      : |
    %configure --disable-static \
               --enable-libflac \
               --enable-libvorbis
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
